### ISSUE TITLE
Integer overflow in C++/05_cppBeginners.cpp

### ISSUE THREAD

**Issue by Sebbyastian** [buckyroberts/Source-Code-from-Tutorials#6]
If two integers are added and the result of adding them causes integer overflow, then the behaviour is undefined.

**Comment by publicarray** [comment]
Integers can only store a number up to 2,147,483,647. You could use an unsigned int to increase this, but than you can only add positive numbers.

source: https://msdn.microsoft.com/en-us/library/s3f49ktz.aspx

FY this is tutorial code i.e. not production ready

**Comment by Sebbyastian** [comment]
Microsoft doesn't define C++. Try again...

**Comment by publicarray** [comment]
No they don't. but it's like looking at MDN for help on JavaScript. Mozilla doesn't define JavaScript. 

Anyway it is good to be mindful of the that integers have a maximum value. But I don't see the integer overflow as a real issue for github, because this repository is for learning c++ from Bucky's tutorials and yes they are simplified, so yes there will be issues.

**Comment by Sebbyastian** [comment]
Since when did Microsoft have the same role in standardisation of C++ as Mozilla (and the parent company, Netscape) did in standardisation of Javascript?

**Comment by publicarray** [comment]
I am a student and I just started learning c++ this semester
